//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyDirectionDbWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int FacultyId { get; set; }
        public int ChairId { get; set; }
        public int SpecialityId { get; set; }
        public int DirectionId { get; set; }
        public int GroupId { get; set; }
        public string Form { get; set; }
    
        public virtual StudyDirection StudyDirection { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual StudyForm StudyForm { get; set; }
    }
}
