//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyDirectionDbWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public string Message { get; set; }
        public int LogId { get; set; }
    }
}
