//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StudyDirectionDbWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Speciality
    {
        public Speciality()
        {
            this.StudyDirections = new HashSet<StudyDirection>();
        }
    
        public int FacultyId { get; set; }
        public int ChairId { get; set; }
        public int SpecialityId { get; set; }
        [MaxLength(50)]
        public string SpecialityName { get; set; }
    
        public virtual Chair Chair { get; set; }
        public virtual ICollection<StudyDirection> StudyDirections { get; set; }
    }
}
