//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyDirectionDbWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyDirection
    {
        public StudyDirection()
        {
            this.Groups = new HashSet<Group>();
        }
    
        public int FacultyId { get; set; }
        public int ChairId { get; set; }
        public int SpecialityId { get; set; }
        public int DirectionId { get; set; }
        public string StudyDirectionName { get; set; }
    
        public virtual ICollection<Group> Groups { get; set; }
        public virtual Speciality Speciality { get; set; }
    }
}
