//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyDirectionDbWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyForm
    {
        public StudyForm()
        {
            this.Groups = new HashSet<Group>();
        }
    
        public string Form { get; set; }
    
        public virtual ICollection<Group> Groups { get; set; }
    }
}
